### ISSUE TITLE
Keybinding instructions not right

### ISSUE THREAD

**Issue by DavidVTurley** [Luke004/Zulu-Assault#9]
Hey Luke,
I love the fact you are bringing this game back on windows 10. Keep up the great work!

I was wondering though about the keybinding. It seems that the bindings in the instructions are not correct. My turn turret right is on X but the turn turret right is on Y. I'm wondring if that is a keyboard layout thing. I'm using a United-States international QWERTY-keyboard.

**Comment by Luke004** [comment]
So you think it should be the opposite around? That might be true.

**Comment by Luke004** [comment]
On my keyboard (German layout) I am using X and Y to rotate the turret. Both keys are in the bottom left of the keyboard as seen in the picture below. The issue might be that your Y is located to the right of the 'T', so it is harder for you to rotate since both keys are far away from eachother. Is that the issue?
![keyboard](https://user-images.githubusercontent.com/28258921/95405429-09032c00-0918-11eb-81ce-b1b5d5b78ea8.png)

**Comment by Luke004** [comment]
I just added a commit that allows a user to switch between two different keyboard layouts (DE, US).
You can use the console (^) to type "keyboard_layout 2" which should give you an english keyboard layout.
Did that fix the issue?

**Comment by BlackHawk1912** [comment]
Why do you use these weird keys anyway? I always hated it when a game is not using "standard" movement keys like WASD, arrow keys or even the numpad.

**Comment by Luke004** [comment]
@BlackHawk1912 Because I am rebuilding this game as accurate as possible, which means that I won't change the controls that the original creator of this game has provided.
